worker: python epl_games_ml_predictions.py
worker2: python laliga_games_ml_predictions.py
worker3: python serie_a_games_ml_predictions.py
worker4: python bundesliga_games_ml_predictions.py
worker5: python epl_player_goals_predictions.py
worker6: python epl_player_assists_predictions.py
worker7: python epl_player_shots_predictions.py
worker8: python nba_games_ml_odds.py
worker9: python nba_player_points_stats.py
worker10: python nba_player_assists_stats.py
worker11: python nba_player_rebounds_stats.py
